language: node_js
node_js:
- 7.9.0
before_script:
- npm install @angular/cli@1.0.0
script:
- npm run test
- npm run packbundle
before_install:
- openssl aes-256-cbc -K $encrypted_ca09a88ec016_key -iv $encrypted_ca09a88ec016_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 120.25.217.56\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
after_success:
- rm -rf ~/.ssh
